- src/index.js
This pull request fixes an error files where it fails to process code blocks with no language set. By changing the fallback value from `null` to `"text"`, the highlighter will continue to process even though `"text"` language may or may not exist.
Tested locally on a Next.js + MDX project by applying a patch via [`patch-package`](https://github.com/ds300/patch-package) using this patchfile:
```patch
diff --git a/node_modules/@atomiks/mdx-pretty-code/dist/mdx-pretty-code.cjs b/node_modules/@atomiks/mdx-pretty-code/dist/mdx-pretty-code.cjs
index 201983f..0755300 100644
--- a/node_modules/@atomiks/mdx-pretty-code/dist/mdx-pretty-code.cjs
+++ b/node_modules/@atomiks/mdx-pretty-code/dist/mdx-pretty-code.cjs
@@ -452,7 +452,7 @@ function createRemarkPlugin(options = {}) {
function …
```
> Fallback code block to 'text' language

- README.md
- index.d.ts
- src/index.js
This PR adds optional support for an array of themes in `shikiOptions.themes`.
The result is multiple code blocks/lines are created for each theme, which can be hidden with css depending on the current color mode.
The implementation is based on `remark-shiki-twoslash`'s https://github.com/shikijs/twoslash/blob/60b638e1299e51bb4cff6cc7484395c67d52a99f/packages/remark-shiki-twoslash/src/index.ts
Also added some docs from https://github.com/shikijs/shiki/blob/main/docs/themes.md#dark-mode-support which outlines the `css-variables` alternative.
> feat: support multiple themes

- package-lock.json
- package.json
- test/fixtures.test.js
- test/fixtures/highlightedLine.md
- test/fixtures/highlightedLines.md
- test/fixtures/highlightedWord.md
- test/fixtures/highlightedWords.md
- test/fixtures/inline.md
- test/fixtures/manyLines.md
- test/fixtures/oneLine.md
- test/results/highlightedLine.html
- test/results/highlightedLines.html
- test/results/highlightedWord.html
- test/results/highlightedWords.html
- test/results/inline.html
- test/results/manyLines.html
- test/results/oneLine.html
- Add Jest snapshot test fixtures
The mdast / hast modules are ESM only. Initially had some trouble getting it working with Jest (and not having to build the lib and compile modules when testing).
Hence the `--experimental-vm-modules`.
> feat: fixture tests

- src/index.js
- test/fixtures/multiWordLanguage.md
- test/results/multiWordLanguage.html
There are some languages supported by shiki that have multiple words, separated by hyphens, like `git-rebase` and `vue-html`.
https://github.com/shikijs/shiki/blob/main/docs/languages.md
> fix: support multi-word languages

- index.d.ts
- src/index.js
- website/pages/index.mdx
At the moment, Rehype Pretty Code only allows the Shiki theme to be configured. By adding a `getHighlighter` option, we can let users configure any present or future Shiki options without having to manually add support for them in Rehype Pretty Code.
For example, it is currently impossible to configure the `langs` option. This change allows the user to pass in a highlighter instance with the `langs` option already set.
The `getHighlighter` function is given the theme options prepared by Rehype Pretty Code, allowing the custom highlighter to support light and dark modes.
> feat: add custom highlighter option

- src/index.js
- test/results/title.html
- add the them to the **title** element- same deal as with `code`, it's needed to hide duplicate title when using multiple themes.
- return the title and pre as children without the extra fragment
fixes #18
> fix: title - add theme, flatten children

- src/wordHighlighter/wordHighlighter.js
> refactor: avoid Array.prototype.at() for old JS runtimes

- index.d.ts
`getHighlighter` should return a promise, not the `Highlighter` directly. Proof:
1. https://github.com/atomiks/rehype-pretty-code/blob/0f23082c11a0ebe00c240cc42998d95c95002c27/src/index.js#L80-L82
2. https://github.com/shikijs/shiki/blob/27691ea35898fd7aec5df524108493c1bb4850aa/packages/shiki/src/highlighter.ts#L42
> Fix custom highlighter typing

- package-lock.json
- package.json
- src/index.js
- test/fixtures.test.js
This aims to prove that the issue that caching was solving doesn't exist, at least not the way you described it in https://github.com/atomiks/rehype-pretty-code/issues/26#issuecomment-1075824800. Highlighter is being created once per the entire tree, not once per each code block in the tree. I added an additional assertion to prove it. (Not sure why `jest.fn` wasn't available, I had to install and import it.)
Let me know what you think!
Fixes #26.
> Don't cache highlighters

- src/index.js
- test/fixtures/title.md
- test/results/title.html
I noticed if you have a path in your title, lik `title="/components/index.js"` that will be picked up by the word regex, and in this example `components` would be highlighted in the code.
I've just done the proceeding matches on the meta with the title removed, should be fine I think. 
Maybe there's a way to do a regex negative lookahead to omit `\/(.*)\/` when inside the quotes but I couldn't figure one out.
> fix: avoid word match inside title

- src/index.js
- test/fixtures.test.js
Since #27 highlighters were being created once per every tree, which resulted in significant performance regression (#36). Between caching once per Node process and not caching at all there is a third option: caching per unified processor, which is exactly what we want! We will still get all the benefits of caching without running into the problems of themes not updating and multiple processors using the same cache.
The two problems I wanted to avoid when I saw caching per Node process were the following:
1. **Multiple unified processors using the same cache.**
```js
import { unified } from 'unified'
import remarkParse form 'remark-parse'
import remarkRehype from 'remark-rehype'
import rehypePrettyCode from 'rehype-pretty-code'
import rehypeStringify from 'rehype-stringify'
function …
```
> fix: cache highlighters per processor

- .gitattributes
- package-lock.json
- src/index.js
- test/fixtures.test.js
- test/fixtures/showLineNumbersStartAt.md
- test/results/highlightPartialNode.html
- test/results/highlightedLine.html
- test/results/highlightedLines.html
- test/results/highlightedMultipleWord.html
- test/results/highlightedMultipleWords.html
- test/results/highlightedWord.html
- test/results/highlightedWords.html
- test/results/highlightedWordsComplex.html
- test/results/inline.html
- test/results/manyLines.html
- test/results/multiWordLanguage.html
- test/results/oneLine.html
- test/results/showLineNumbers.html
- test/results/showLineNumbersStartAt.html
- test/results/title.html
- test/results/undefined.html
- test/results/unknownLanguage.html
- website/pages/index.mdx
fixes #44  
**New Syntax: showLineNumbers{\<number\>}**
````
```text showLineNumbers{20}
//some text
```
````
Line numbers of this code block will be start counting from 20
If no start line number provided, it will work the same as before
````
```text showLineNumbers
//some text
```
````
> feat: add custom line number

- index.d.ts
- src/index.js
- test/fixtures.test.js
- test/fixtures/filterMetaString.md
- test/results/filterMetaString.html
If the meta string also has custom config by you, it may cause issues with word highlighting or other features of `rehype-pretty-code`.
So Nextra would specify:
```js
const options = {
filterMetaString: (string) => string.replace(/filename=".*"/, ''),
};
```
@B2o5T
> feat: `filterMetaString` option

- src/index.js
- test/results/showLineNumbers.html
- test/results/showLineNumbersStartAt.html
- website/pages/index.mdx
CSS variable seems problematic to `@next/mdx` and `@astrojs/mdx` (at least what I'm tested), move to data attribute.
```css
code > .line::before {
width: 1rem;
}
code[data-line-numbers-max-digits="2"] > .line::before {
width: 2rem;
}
code[data-line-numbers-max-digits="3"] > .line::before {
width: 3rem;
}
// ...
```
> fix: move `lineNumbersMaxDigits` from CSS variable to data attribute

- src/index.js
- test/fixtures/keepBackground.md
- test/results/keepBackground.html
Hi!
This PR  uses the theme background color as the inline background when the keepBackground option is true. In the current version, the inline background color does not change.
> feat: support keepBackground option in inline

- src/index.js
- test/fixtures/highlightedLinesWithShowLineNumbersAt.md
- test/results/highlightedLinesWithShowLineNumbersAt.html
When `showLineNumbers` exists with a value to start at, like `showLineNumbers{3}`, the line highlighter potentially grabs that number instead of the appropriate line highlight group, causing line highlights to not function correctly.
The new regex essentially checks to see if there are any characters before the `{` other than white space and filters them out. If there is a white space before the `{`, it's the correct group for line highlights.
If you run the additional test, but without the changes in `src/index.js`, the test fails. It then passes with the changes.
> fix: change `lineNumbers` regex to respect positioning/existence of `showLineNumbers{x}`

- src/index.js
- test/fixtures.test.js
- test/fixtures/showLineNumbersStartAtMultipleTheme.md
- test/results/showLineNumbersStartAtMultipleTheme.html
There is an issue with the functionality of specifying the starting line number when using `showLineNumbers{n}` with Multiple Themes. [#80](link-to-issue)
In the case of applying multiple themes, the `index` of the code element node with the second theme is 1. Therefore, it fails to pass the condition `if (index === 0)`, resulting in the failure of the logic that sets the counter-set as an inline style.
The condition `if (index === 0)` has been removed. It has been verified that the tests are passing.
Are there any potential issues or concerns with removing the condition `if (index === 0)`?
> fix: showLineNumbers{n} with Multiple theme bug

- website/tailwind.config.js
This trick is used so that tailwind typography plugin doesn't add backticks around inline code, however it was adding a tiny bit of vertical scroll to code blocks unnecesarily when using firefox. Instead of setting `content: "" !important` we can use `content: unset !important` instead.
Before:
After:
> fix: remove unnecessary scrollbars on website when using firefox

- src/index.ts
- test/results/ansi.html
- test/results/caption.html
- test/results/defaultLang.block=js.html
- test/results/defaultLang.inline=js&block=js.html
- test/results/defaultLang.inline=js.html
- test/results/defaultLang.js.html
- test/results/diff.html
- test/results/filterMetaString.html
- test/results/highlightChars.html
- test/results/highlightCharsById.html
- test/results/highlightCharsComplex.html
- test/results/highlightCharsRange.html
- test/results/highlightMultipleChars.html
- test/results/highlightPartialNode.html
- test/results/highlightedLine.html
- test/results/highlightedLines.html
- test/results/highlightedLinesWithShowLineNumbersAt.html
- test/results/highlightedMultipleCharsRange.html
- test/results/keepBackground.html
- test/results/manyLines.html
- test/results/multiWordLanguage.html
- test/results/oneLine.html
- test/results/showLineNumbers.html
- test/results/showLineNumbersStartAt.html
- test/results/showLineNumbersStartAtMultipleTheme.html
- test/results/title.html
- test/results/undefined.html
- test/results/unknownLanguage.html
Omitting the `className` completely means that the class names that the shiki processors inject as `createDiffProcessor`, `createHighlightProcessor`, etc, also get omitted.
Just making a change here to only omit the class we want (aka `"line"`).
This seemed to break between versions 0.9 and 0.10.
> fix: line class omission

- src/index.ts
- test/fixtures/highlightChars.md
- test/results/highlightChars.html
Partially addresses #70 (since you can't highlight `/` and `"` simultaneously still - Prettier seems to remove `\` from the metastring so escaping doesn't seem smoothly possible...)
> feat: allow double quotes as chars delimiter

- package-lock.json
- package.json
- src/index.ts
In order to use some Shikiji features like [Twoslash's `explicitTrigger`](https://shikiji.netlify.app/packages/twoslash#explicit-trigger), we need to pass the code block's raw `meta` to Shikiji.
> feat: pass raw meta to shikiji

- src/index.ts
- test/fixtures/unknownLanguage.md
- test/results/unknownLanguage.html
`plaintext` language renders another `<span>` so the children empty check fails. `toString(node)` being empty works for both
Fix #157
> fix: collapsing lines with plaintext lang with grid true

- src/index.ts
@ben519 is this enough to fix the issue? It doesn't appear there's any programming language that uses `math` so..
Fix #155
> fix: ignore math lang

- src/index.ts
- test/fixtures/highlightedMultipleCharsRange.md
- test/results/highlightedMultipleCharsRange.html
Fixes https://github.com/atomiks/rehype-pretty-code/issues/166
> fix: rangeless multi chars highlighting

- src/index.ts
- test/fixtures/highlightedLinesWithShowLineNumbersAt.md
- test/results/highlightedLinesWithShowLineNumbersAt.html
This PR fixes an issue where combining `showLineNumbers{number}` with line highlighting would cause the start line number to be highlighted when it shouldn't be.
Included is an expanded test fixture that demonstrates the issue, which can be fixed by using a negative lookbehind in the regex used to find highlighted line numbers in the meta.
**Before this PR:**
**After this PR:**
> Fix start line numbers being highlighted

- examples/astro/src/globals.css
- examples/astro/src/pages/page.astro
- examples/sveltekit/src/routes/+page.svelte
- website/src/app/globals.css
Resolves #210 
This hides the scrollbar when there is sufficient space, which fixes the layout of the code component on the main website as well as a few examples.
Main page (Before / After)
Astro Example
Svelte Example
> Change overflow-x from scroll to auto

- .changeset/perfect-onions-dream.md
- docs/src/content/docs/index.mdx
- examples/next/src/app/index.mdx
- packages/core/src/index.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/fixtures/bypassInlineCode.md
- packages/core/test/results/bypassInlineCode.html
Allows bypassing inline code blocks from being transformed by `rehype-pretty-code`.
Config:
```js /rehypePrettyCode/
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import rehypeStringify from "rehype-stringify";
import rehypePrettyCode from "rehype-pretty-code";
async function main() {
const file = await unified()
.use(remarkParse)
.use(remarkRehype)
.use(rehypePrettyCode, {
bypassInlineCode: true
})
.use(rehypeStringify)
.process("`const numbers = [1, 2, 3]{:js}`");
console.log(String(file));
}
main();
```
Input:
~~~md
```js
const x = true;
```
`const x = true;{:js,bypassInlineCode:true}`
~~~
Output:
```html
<figure data-rehype-pretty-code-figure="">
<pre
style="background-color: #24292e; color: #e1e4e8"
tabindex="0" …
```
> Bypass inline code

- docs/src/content/docs/index.mdx
The example css did not work for conditional showLineNumbers.
Used the css from the website that shows the working example.
Line 75-83 (example i used)
https://github.com/rehype-pretty/rehype-pretty-code/blob/master/examples/astro/src/globals.css
Old PR
https://github.com/rehype-pretty/rehype-pretty-code/pull/203
Testimonial
https://github.com/rehype-pretty/rehype-pretty-code/pull/203#issuecomment-2274978414
> fix: error in showLineNumbers example

- docs/src/content/docs/index.mdx
Removed an unnecessary import statement from an example Next.js config file in the home page.
> docs(page:home): remove unneeded imports

- .changeset/cool-carpets-suffer.md
- packages/core/src/index.ts
The `getHighlighter` function has been deprecated and leads to memory issues from what I read.
Closes #255
> use getSingletonHighlighter
